export const mockLeads = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    company: "TechCorp Inc",
    source: "Website",
    status: "new",
    value: 15000,
    createdAt: "2023-12-01",
    lastContact: "2023-12-01",
    assignedTo: "John Doe",
    notes: "Interested in enterprise package"
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "m.chen@startup.io",
    phone: "+1 (555) 234-5678",
    company: "StartupIO",
    source: "LinkedIn",
    status: "contacted",
    value: 8500,
    createdAt: "2023-11-28",
    lastContact: "2023-11-30",
    assignedTo: "Jane Smith",
    notes: "Follow up needed on pricing"
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily@designco.com",
    phone: "+1 (555) 345-6789",
    company: "DesignCo",
    source: "Referral",
    status: "qualified",
    value: 22000,
    createdAt: "2023-11-25",
    lastContact: "2023-12-02",
    assignedTo: "John Doe",
    notes: "Ready to schedule demo"
  },
  {
    id: 4,
    name: "David Wilson",
    email: "dwilson@corp.com",
    phone: "+1 (555) 456-7890",
    company: "Corp Solutions",
    source: "Google Ads",
    status: "proposal",
    value: 35000,
    createdAt: "2023-11-20",
    lastContact: "2023-12-01",
    assignedTo: "Jane Smith",
    notes: "Proposal sent, awaiting response"
  },
  {
    id: 5,
    name: "Lisa Thompson",
    email: "lisa@marketing.com",
    phone: "+1 (555) 567-8901",
    company: "Marketing Pro",
    source: "Cold Email",
    status: "closed-won",
    value: 12000,
    createdAt: "2023-11-15",
    lastContact: "2023-11-29",
    assignedTo: "John Doe",
    notes: "Deal closed successfully"
  },
  {
    id: 6,
    name: "Robert Brown",
    email: "rbrown@tech.com",
    phone: "+1 (555) 678-9012",
    company: "Tech Solutions",
    source: "Website",
    status: "closed-lost",
    value: 18000,
    createdAt: "2023-11-10",
    lastContact: "2023-11-25",
    assignedTo: "Jane Smith",
    notes: "Went with competitor"
  }
];