import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner';

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Icetr.ai | AI Powered Cold Outreach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        captcha: {
          theme: "auto",
          size: "flexible",
          language: "en-US",
        },
      }}
      signInForceRedirectUrl="/home"
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${roboto.className} antialiased`}>
          <ThemeProvider>
            {children}
            <Toaster theme="dark" richColors/>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
