export const pricingPlans = [
  {
    name: "Starter",
    price: "$79",
    period: "/month",
    description: "Perfect for solo entrepreneurs and small teams",
    features: [
      "Up to 3 users",
      "Up to 1000 leads",
      "5 campaigns",
      "1 training scenario",
      "Call recording & transcripts",
      "AI cold call training",
      "Calendly integration",
      "Email support",
      "Free number included",
    ],
    cta: "Start Today!",
    popular: false,
    stripePriceId: "price_1RrpQyLHmVqPdFvXsc4WT2s7",
    yearlyStripePriceId: "price_1RsyusLHmVqPdFvXo5o96kCL",
  },
  {
    name: "Growth",
    price: "$249",
    description:
      "For teams ready to level up their outreach and lead management.",
    period: "/month",
    features: [
      "Everything in Starter",
      "Up to 10 users",
      "Up to 10,000 leads",
      "25 campaigns",
      "10 training scenarios",
      "Auto lead assignment",
      "Inbound Call Handling",

      "Standard integrations",
    ],
    cta: "Start Today!",
    popular: true,
    stripePriceId: "price_1RrrssLHmVqPdFvXLkBzejjI",
    yearlyStripePriceId: "price_1RsyvtLHmVqPdFvXJY0IRs5v",
  },
  {
    name: "Professional",
    price: "$599",
    period: "/month",
    description: "Ideal for growing sales teams and agencies",
    features: [
      "Everything in Growth",
      "Up to 20 users",
      "Up to 20,000 leads",
      "50 campaigns",
      "20 training scenarios",
      "Auto lead assignment",
      "Team collaboration tools",
      "Multi-user access controls",
      "Priority support",
    ],
    cta: "Start Today!",
    popular: false,
    stripePriceId: "price_1RrpSNLHmVqPdFvXmABY4gv0",
    yearlyStripePriceId: "price_1RsywvLHmVqPdFvXIdAE8tdL",
  },
];
